language: rust
branches:
  only:
  - master
matrix:
  include:
    - name: "stable rust + rustfmt + clippy"
      rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt -- --check
        - cargo clippy
        - cargo build
        - cargo test
    - name: "nightly rust"
      rust: nightly
      script:
        - cargo build
        - cargo test
